spring:
  config:
    activate:
      on-profile: dev

mongodb:
  host: 192.168.100.100
  port: 31017
  authentication-database: admin
  username: root
  password: devqlalfqjsgh486
  database: message


# kafka
kafka:
  bootstrap-servers: 192.168.100.201:9094,192.168.100.202:9094,192.168.100.203:9094
  compression-type: zstd
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: SCRAM-SHA-512
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="Jkco2eqlPx";

  # Consumer 설정
  consumer:
    group-id: message-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    auto-commit-interval: 5000
    max-poll-records: 500
    fetch-min-bytes: 1
    fetch-max-wait: 500
    heartbeat-interval: 3000
    session-timeout: 10000
    max-poll-interval: 300000

  # 토픽 설정
  topic:
    informational:
      email: "dev.message-service.email.informational"
      push: "dev.message-service.push.informational"
    advertising:
      email: "dev.message-service.email.advertising"
      push: "dev.message-service.push.advertising"

email:
  host: smtp.daum.net
  port: 465
  username: wondookong
  password: xxvdlkdebofpfhek
  transport-protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
    ssl:
      enable: true
      trust: smtp.daum.net
  debug: true

kms:
  token: c07139d0f57d841f1aa4589b0d4b653cf8fbbb57b3b7ac52d07776129e4e95ae
  url: https://kms.kwt.co.kr/api/secrets
  secretKey: exchange