spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      host: 192.168.100.100
      port: 31017
      authentication-database: admin
      username: root
      password: devqlalfqjsgh486
      database: message

# kafka
kafka:
  bootstrap-servers: kafka-controller-headless.kafka:9092, kafka-controller-headless.kafka:9093, kafka-controller-headless.kafka:9094
  compression-type: zstd
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: SCRAM-SHA-512
    jaas:
      config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="Jkco2eqlPx";
  acks: "all"
  retries: 3
  linger-ms: 20
  topic:
    informational:
      email: "prod.message-service.email.informational"
      push: "prod.message-service.push.informational"
    advertising:
      email: "prod.message-service.email.advertising"
      push: "prod.message-service.push.advertising"